# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/deep_learning_biophysics',
                'doc_host': 'https://DiTscho.github.io',
                'git_url': 'https://github.com/DiTscho/deep_learning_biophysics',
                'lib_path': 'deep_learning_biophysics'},
  'syms': {'deep_learning_biophysics.core': {'deep_learning_biophysics.core.foo': ('core.html#foo', 'deep_learning_biophysics/core.py')}}}